### ISSUE TITLE
Great contribution to the community!

### ISSUE THREAD

**Issue by patripfr** [PengYu-Team/GEODE_dataset#1]
Thanks a lot for this extensive dataset and the thorough evaluation! Great to see that lidar degeneracy research is starting to gain traction and become a larger field in the community! :)

**Comment by DapengFeng** [comment]
Thank you for your attention to our work. We hope this dataset will be beneficial to the community! :)

**Comment by DapengFeng** [comment]
Hi, @patripfr. Welcome to create a PR at https://github.com/thisparticle/Awesome-Algorithms-Against-Degeneracy, an awesome collection for degeneracy SLAM.
