### ISSUE TITLE
Metadata for ouster

### ISSUE THREAD

**Issue by nkhedekar** [PengYu-Team/GEODE_dataset#4]
Hi, 
Thank you for your contribution! :slightly_smiling_face: 
Could you also share the metadata.json file for the OS1-64 used in the Beta platform? (Or in case already shared, let me know where I can find it?)
Thanks!

**Comment by thisparticle** [comment]
Hello, I haven’t uploaded this file yet as I need assistance from my collaborators to do so. I have recently changed my organization for research work. I will share the link once the file is uploaded.
Thank you for your patience!

**Comment by thisparticle** [comment]
The metadata.json file for the OS1-64 used in the Beta platform can be accessed via the following link: [Google Drive](https://drive.google.com/file/d/1mkB0DFR0Fv3YcI1frnZNxi5AEhObKXbA/view?usp=drive_link).
