### ISSUE TITLE
投哪的 IJRR？

### ISSUE THREAD

**Issue by snakehaihai** [PengYu-Team/GEODE_dataset#8]
投哪的 IJRR？

**Comment by snakehaihai** [comment]
你忘了cite 一些最新的工作 比如最新的 IJRR的 MARS-LVIG Dataset  还有CVPR的 MCD dataset

**Comment by thisparticle** [comment]
> 投哪的 IJRR？

是的  :smile:

**Comment by thisparticle** [comment]
> 你忘了cite 一些最新的工作 比如最新的 IJRR的 MARS-LVIG Dataset https://mars.hku.hk/dataset.html 还有CVPR的 MCD dataset https://mcdviral.github.io/ 还有 GauUscene https://saliteta.github.io/CUHKSZ_SMBU/

哈哈哈哈您的感谢提醒，要有机会rebuttal改论文的时候考虑添加 :blush:

**Comment by thisparticle** [comment]
> 做的不错的。之后准备拓展搞语义，object， 大规模具身数据集 之类么？

之前有考虑过做感知的数据集，但是没开始搞。大佬有建议吗哈哈哈哈 :star2:

**Comment by snakehaihai** [comment]
> 过做感知的数据集，但是没开始搞。大佬有建

把你现在的拓展一下  其他真值   包括   语义 还有那些open vocab 模型 还有object detection  等一系列的。 参考MCD。纯 SLAM 上分有点慢

**Comment by thisparticle** [comment]
> > 过做感知的数据集，但是没开始搞。大佬有建
> 
> 把你现在的拓展一下 其他真值 包括 语义 还有那些open vocab 模型 还有object detection 等一系列的。 参考MCD。纯 SLAM 上分有点慢

学到了 :thumbsup:
